spring.application.name=profileDemo

app.welcome.message = Local: Hi this is my aplication
app.welcome.code = 200
server.port = 8080
app.welcome.users = Rahul,Anubhav,Neha
spring.profiles.active=prod

